# NumPy
Short for Numerical Python, NumPy is a foundational package for numerical computing in Python, ndarray is an efficient multidimensional array provinding fast array oriented operations

In [1]:
import numpy as np

In [2]:
a = np.arange(1000000)
l = list(range(1000000))

In [3]:
%timeit for _ in range(100): a2 = a * 2

254 ms ± 2.73 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [4]:
%timeit for _ in range(100): l2 = l * 2

2.14 s ± 22.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Creating ndarrays in numpy

 np.array(), np.arange(), np.ones(), np.zeros(), np.full(), np.empty(), np.eye() / identity()

In [5]:
data = [1,2,3,4,5]
a1 = np.array(data)
a1

array([1, 2, 3, 4, 5])

In [6]:
type(a1)

numpy.ndarray

In [7]:
data = [[1,2,3],[4,5,6]]
a1 = np.array(data)
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
data = [[1,2,3],[4,5,6]]
a1 = np.array(data, dtype = np.float64)
a1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [9]:
a1.shape

(2, 3)

In [10]:
a1.dtype

dtype('float64')

In [12]:
a1.ndim

2

In [14]:
a1 = np.arange(10)

In [15]:
type(a1)

numpy.ndarray

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.full((2,3), fill_value = 5)

array([[5, 5, 5],
       [5, 5, 5]])

In [20]:
np.empty(10)

array([1.38686588e-311, 2.12448228e-322, 0.00000000e+000, 0.00000000e+000,
       1.06811354e-306, 1.16095484e-028, 7.52736939e+252, 1.47278596e+179,
       9.08367237e+223, 1.16466228e-028])

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Data Types in numpy

int(8,16,32,64),uint(8,16,32,64), float(16,32,64,128), complex(64,128,256), bool, object, string_, unicode_

In [22]:
np.arange(5, dtype = np.int32)

array([0, 1, 2, 3, 4])

In [23]:
np.arange(5, dtype = np.float64)

array([0., 1., 2., 3., 4.])

In [24]:
a = np.array([1, 2.5,3.8])
b = a.astype(np.int32)
b

array([1, 2, 3])

## Arithmatic using numpy ndarrays

In [25]:
a1 = np.array([1,2,3,4,5])
a1 + 2

array([3, 4, 5, 6, 7])

In [26]:
a1

array([1, 2, 3, 4, 5])

In [27]:
a1 + a1

array([ 2,  4,  6,  8, 10])

In [28]:
a1

array([1, 2, 3, 4, 5])

In [29]:
a1 * 2

array([ 2,  4,  6,  8, 10])

In [30]:
a2 = a1 * 2

In [31]:
a2

array([ 2,  4,  6,  8, 10])

In [34]:
a2 // 2

array([1, 2, 3, 4, 5], dtype=int32)

In [36]:
6 // a1

array([6, 3, 2, 1, 1], dtype=int32)

In [37]:
a1 ** 2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [38]:
a2 = np.array([2,1,4,3,5])

In [39]:
a1 > a2

array([False,  True, False,  True, False])

In [40]:
a1 < a2

array([ True, False,  True, False, False])

## Indexing and Slicing

In [41]:
a = np.arange(10)

In [42]:
a[5]

5

In [43]:
a[0]

0

In [44]:
a[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [45]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a[::2]

array([0, 2, 4, 6, 8])

In [51]:
a2 = np.arange(11)
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
a2[:3]=11

In [53]:
a2

array([11, 11, 11,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
a2[:] = 22

In [55]:
a2

array([22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22])

In [56]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
c = a1.copy()

In [58]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
c[:3] = 33
c

array([33, 33, 33,  3,  4,  5,  6,  7,  8,  9])

In [60]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
d = a1
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
d[:3] = 44
d

array([44, 44, 44,  3,  4,  5,  6,  7,  8,  9])

In [63]:
a1

array([44, 44, 44,  3,  4,  5,  6,  7,  8,  9])

In [66]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [68]:
a[0]

array([1, 2, 3, 4, 5])

## Reshaping and transposing

In [164]:
a = np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [165]:
a1 = a.reshape((4,4))

In [166]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [72]:
a2 = a.reshape((2,8))
a2

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [73]:
a3 = a.reshape((3,8))

ValueError: cannot reshape array of size 16 into shape (3,8)

In [167]:
a1.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [168]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [169]:
a1 = a1.T

In [170]:
a1

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [78]:
np.dot(a1,a1.T)

array([[224, 248, 272, 296],
       [248, 276, 304, 332],
       [272, 304, 336, 368],
       [296, 332, 368, 404]])

In [171]:
a1

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [174]:
a1.swapaxes(0,1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [83]:
a1 = a1.T

In [84]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [159]:
a1.swapaxes(0,1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [163]:
a1.swapaxes(0,1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Functions for ndarrays

In [87]:
a = np.array([3,2,5,8,7,3,4,9])
a

array([3, 2, 5, 8, 7, 3, 4, 9])

In [88]:
a.sort()

In [89]:
a

array([2, 3, 3, 4, 5, 7, 8, 9])

In [90]:
np.square(a)

array([ 4,  9,  9, 16, 25, 49, 64, 81], dtype=int32)

In [93]:
a2 = np.square(a)

In [94]:
np.sqrt(a2)

array([2., 3., 3., 4., 5., 7., 8., 9.])

In [95]:
np.abs([-1,-2,-3])

array([1, 2, 3])

In [96]:
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])
np.add(a1,a2)

array([ 6,  8, 10, 12])

In [97]:
a1 + a2

array([ 6,  8, 10, 12])

In [98]:
np.subtract(a2,a1)

array([4, 4, 4, 4])

In [99]:
np.maximum(a1,a2)

array([5, 6, 7, 8])

In [100]:
a3 = np.array([9,2,3,9])
a4 = np.array([5,6,7,8])

In [101]:
np.maximum(a3,a4)

array([9, 6, 7, 9])

In [102]:
np.minimum(a3,a4)

array([5, 2, 3, 8])

In [103]:
np.power(a1,a2)

array([    1,    64,  2187, 65536], dtype=int32)

In [104]:
np.greater(a1,a2)

array([False, False, False, False])

In [105]:
np.greater(a3,a4)

array([ True, False, False,  True])

In [106]:
np.less(a3,a4)

array([False,  True,  True, False])

## Mathematical and Statistical Functions

In [107]:
a = np.array([1,2,3,4,5,6,7,8,9])
a.mean()

5.0

In [108]:
np.mean(a)

5.0

In [109]:
a.sum()

45

In [110]:
a.min()

1

In [111]:
a.max()

9

In [112]:
a.var()

6.666666666666667

In [113]:
a.std()

2.581988897471611

In [114]:
a.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [115]:
a.cumprod()

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)

In [125]:
a = np.arange(25)
a = a.reshape((5,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [124]:
a.mean(axis=1)

array([ 2.,  7., 12., 17., 22.])

In [127]:
a.mean(axis=0)

array([10., 11., 12., 13., 14.])

In [128]:
a1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [129]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [130]:
a1.dot(a2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [131]:
np.dot(a1,a2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [132]:
from numpy.linalg import det, inv, eig

In [133]:
a = np.arange(16).reshape((4,4))

In [157]:
a

array([0.93630626, 0.6135402 , 0.01281697, 0.8602    , 0.96403898,
       0.32855974, 0.71510097, 0.68370657, 0.14614182, 0.63336049])

In [158]:
a * 2

array([1.87261251, 1.22708039, 0.02563393, 1.72040001, 1.92807796,
       0.65711947, 1.43020195, 1.36741315, 0.29228365, 1.26672097])

In [135]:
det(a)

-2.9582283945787796e-30

In [136]:
inv(a)

array([[ 9.00719925e+14, -4.50359963e+14, -1.80143985e+15,
         1.35107989e+15],
       [-2.40191980e+15,  2.70215978e+15,  1.80143985e+15,
        -2.10167983e+15],
       [ 2.10167983e+15, -4.05323966e+15,  1.80143985e+15,
         1.50119988e+14],
       [-6.00479950e+14,  1.80143985e+15, -1.80143985e+15,
         6.00479950e+14]])

In [137]:
eig(a)

(array([ 3.24642492e+01, -2.46424920e+00,  1.92979794e-15, -4.09576009e-16]),
 array([[-0.11417645, -0.7327781 ,  0.54500164,  0.00135151],
        [-0.3300046 , -0.28974835, -0.68602671,  0.40644504],
        [-0.54583275,  0.15328139, -0.2629515 , -0.8169446 ],
        [-0.76166089,  0.59631113,  0.40397657,  0.40914805]]))

In [152]:
a = np.random.randint(100)

In [153]:
a

88

In [155]:
a = np.random.rand(10)

In [156]:
a

array([0.93630626, 0.6135402 , 0.01281697, 0.8602    , 0.96403898,
       0.32855974, 0.71510097, 0.68370657, 0.14614182, 0.63336049])